<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Acme.Libraries.Events</AssemblyName>
    <RootNamespace>Acme.Libraries.Events</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MagicCSharp" />
    <PackageReference Include="MagicCSharp.Events" />
  </ItemGroup>

</Project>
